// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: mailbox/v1/mailbox.proto

package mailboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MailboxService_GetMessage_FullMethodName               = "/mailbox.v1.MailboxService/GetMessage"
	MailboxService_ListMessages_FullMethodName             = "/mailbox.v1.MailboxService/ListMessages"
	MailboxService_SearchMessages_FullMethodName           = "/mailbox.v1.MailboxService/SearchMessages"
	MailboxService_GetThread_FullMethodName                = "/mailbox.v1.MailboxService/GetThread"
	MailboxService_GetReplies_FullMethodName               = "/mailbox.v1.MailboxService/GetReplies"
	MailboxService_SendMessage_FullMethodName              = "/mailbox.v1.MailboxService/SendMessage"
	MailboxService_UpdateFlags_FullMethodName              = "/mailbox.v1.MailboxService/UpdateFlags"
	MailboxService_MoveMessage_FullMethodName              = "/mailbox.v1.MailboxService/MoveMessage"
	MailboxService_DeleteMessage_FullMethodName            = "/mailbox.v1.MailboxService/DeleteMessage"
	MailboxService_RestoreMessage_FullMethodName           = "/mailbox.v1.MailboxService/RestoreMessage"
	MailboxService_PermanentlyDeleteMessage_FullMethodName = "/mailbox.v1.MailboxService/PermanentlyDeleteMessage"
	MailboxService_AddTag_FullMethodName                   = "/mailbox.v1.MailboxService/AddTag"
	MailboxService_RemoveTag_FullMethodName                = "/mailbox.v1.MailboxService/RemoveTag"
	MailboxService_MarkAllRead_FullMethodName              = "/mailbox.v1.MailboxService/MarkAllRead"
	MailboxService_BulkUpdateFlags_FullMethodName          = "/mailbox.v1.MailboxService/BulkUpdateFlags"
	MailboxService_BulkMove_FullMethodName                 = "/mailbox.v1.MailboxService/BulkMove"
	MailboxService_BulkDelete_FullMethodName               = "/mailbox.v1.MailboxService/BulkDelete"
	MailboxService_BulkPermanentlyDelete_FullMethodName    = "/mailbox.v1.MailboxService/BulkPermanentlyDelete"
	MailboxService_BulkAddTag_FullMethodName               = "/mailbox.v1.MailboxService/BulkAddTag"
	MailboxService_BulkRemoveTag_FullMethodName            = "/mailbox.v1.MailboxService/BulkRemoveTag"
	MailboxService_ComposeDraft_FullMethodName             = "/mailbox.v1.MailboxService/ComposeDraft"
	MailboxService_UpdateDraft_FullMethodName              = "/mailbox.v1.MailboxService/UpdateDraft"
	MailboxService_ListDrafts_FullMethodName               = "/mailbox.v1.MailboxService/ListDrafts"
	MailboxService_DeleteDraft_FullMethodName              = "/mailbox.v1.MailboxService/DeleteDraft"
	MailboxService_SendDraft_FullMethodName                = "/mailbox.v1.MailboxService/SendDraft"
	MailboxService_GetStats_FullMethodName                 = "/mailbox.v1.MailboxService/GetStats"
	MailboxService_UnreadCount_FullMethodName              = "/mailbox.v1.MailboxService/UnreadCount"
	MailboxService_ListFolders_FullMethodName              = "/mailbox.v1.MailboxService/ListFolders"
	MailboxService_StreamNotifications_FullMethodName      = "/mailbox.v1.MailboxService/StreamNotifications"
)

// MailboxServiceClient is the client API for MailboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MailboxService exposes email-like messaging operations for a user mailbox.
// Every RPC is scoped to a user identified by user_id in the request.
// Access control is delegated to the SecurityGuard configured on the server.
type MailboxServiceClient interface {
	// GetMessage retrieves a single message by ID.
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// ListMessages lists messages in a folder with pagination.
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	// SearchMessages performs full-text search across a user's messages.
	SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	// GetThread returns all messages belonging to a thread, ordered by creation time.
	GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	// GetReplies returns all direct replies to a message.
	GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	// SendMessage sends a message without going through the draft workflow.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// UpdateFlags changes the read or archived status of a message.
	UpdateFlags(ctx context.Context, in *UpdateFlagsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// MoveMessage moves a message to a different folder.
	MoveMessage(ctx context.Context, in *MoveMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteMessage moves a message to trash.
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RestoreMessage restores a message from trash.
	RestoreMessage(ctx context.Context, in *RestoreMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PermanentlyDeleteMessage hard-deletes a message from trash.
	PermanentlyDeleteMessage(ctx context.Context, in *PermanentlyDeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AddTag adds a tag to a message.
	AddTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RemoveTag removes a tag from a message.
	RemoveTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// MarkAllRead marks all unread messages in a folder as read.
	MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// BulkUpdateFlags changes the read/archived status of multiple messages.
	BulkUpdateFlags(ctx context.Context, in *BulkUpdateFlagsRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// BulkMove moves multiple messages to a folder.
	BulkMove(ctx context.Context, in *BulkMoveRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// BulkDelete moves multiple messages to trash.
	BulkDelete(ctx context.Context, in *BulkDeleteRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// BulkPermanentlyDelete hard-deletes multiple messages from trash.
	BulkPermanentlyDelete(ctx context.Context, in *BulkPermanentlyDeleteRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// BulkAddTag adds a tag to multiple messages.
	BulkAddTag(ctx context.Context, in *BulkTagRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// BulkRemoveTag removes a tag from multiple messages.
	BulkRemoveTag(ctx context.Context, in *BulkTagRequest, opts ...grpc.CallOption) (*BulkResultResponse, error)
	// ComposeDraft creates and saves a new draft.
	ComposeDraft(ctx context.Context, in *ComposeDraftRequest, opts ...grpc.CallOption) (*DraftResponse, error)
	// UpdateDraft updates fields of an existing draft.
	// Only non-empty fields are applied; empty string fields are left unchanged.
	UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*DraftResponse, error)
	// ListDrafts lists all drafts for a user with pagination.
	ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*DraftListResponse, error)
	// DeleteDraft permanently deletes a draft.
	DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SendDraft sends an existing draft.
	SendDraft(ctx context.Context, in *SendDraftRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// GetStats returns aggregate statistics for a user's mailbox.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// UnreadCount returns the total number of unread messages for a user.
	UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// ListFolders lists all folders (system and custom) in a user's mailbox.
	ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*FolderListResponse, error)
	// StreamNotifications streams real-time notification events for a user.
	// The stream stays open until the client disconnects or the context is cancelled.
	// Pass last_event_id to replay missed events on reconnect.
	StreamNotifications(ctx context.Context, in *StreamNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationEvent], error)
}

type mailboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailboxServiceClient(cc grpc.ClientConnInterface) MailboxServiceClient {
	return &mailboxServiceClient{cc}
}

func (c *mailboxServiceClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MailboxService_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, MailboxService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, MailboxService_SearchMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, MailboxService_GetThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, MailboxService_GetReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MailboxService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) UpdateFlags(ctx context.Context, in *UpdateFlagsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_UpdateFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) MoveMessage(ctx context.Context, in *MoveMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_MoveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) RestoreMessage(ctx context.Context, in *RestoreMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_RestoreMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) PermanentlyDeleteMessage(ctx context.Context, in *PermanentlyDeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_PermanentlyDeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) AddTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_AddTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) RemoveTag(ctx context.Context, in *TagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_RemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, MailboxService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkUpdateFlags(ctx context.Context, in *BulkUpdateFlagsRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkUpdateFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkMove(ctx context.Context, in *BulkMoveRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkDelete(ctx context.Context, in *BulkDeleteRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkPermanentlyDelete(ctx context.Context, in *BulkPermanentlyDeleteRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkPermanentlyDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkAddTag(ctx context.Context, in *BulkTagRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkAddTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) BulkRemoveTag(ctx context.Context, in *BulkTagRequest, opts ...grpc.CallOption) (*BulkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResultResponse)
	err := c.cc.Invoke(ctx, MailboxService_BulkRemoveTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) ComposeDraft(ctx context.Context, in *ComposeDraftRequest, opts ...grpc.CallOption) (*DraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftResponse)
	err := c.cc.Invoke(ctx, MailboxService_ComposeDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*DraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftResponse)
	err := c.cc.Invoke(ctx, MailboxService_UpdateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) ListDrafts(ctx context.Context, in *ListDraftsRequest, opts ...grpc.CallOption) (*DraftListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftListResponse)
	err := c.cc.Invoke(ctx, MailboxService_ListDrafts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) DeleteDraft(ctx context.Context, in *DeleteDraftRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailboxService_DeleteDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) SendDraft(ctx context.Context, in *SendDraftRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MailboxService_SendDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MailboxService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) UnreadCount(ctx context.Context, in *UnreadCountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, MailboxService_UnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) ListFolders(ctx context.Context, in *ListFoldersRequest, opts ...grpc.CallOption) (*FolderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FolderListResponse)
	err := c.cc.Invoke(ctx, MailboxService_ListFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailboxServiceClient) StreamNotifications(ctx context.Context, in *StreamNotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotificationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MailboxService_ServiceDesc.Streams[0], MailboxService_StreamNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNotificationsRequest, NotificationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_StreamNotificationsClient = grpc.ServerStreamingClient[NotificationEvent]

// MailboxServiceServer is the server API for MailboxService service.
// All implementations must embed UnimplementedMailboxServiceServer
// for forward compatibility.
//
// MailboxService exposes email-like messaging operations for a user mailbox.
// Every RPC is scoped to a user identified by user_id in the request.
// Access control is delegated to the SecurityGuard configured on the server.
type MailboxServiceServer interface {
	// GetMessage retrieves a single message by ID.
	GetMessage(context.Context, *GetMessageRequest) (*MessageResponse, error)
	// ListMessages lists messages in a folder with pagination.
	ListMessages(context.Context, *ListMessagesRequest) (*MessageListResponse, error)
	// SearchMessages performs full-text search across a user's messages.
	SearchMessages(context.Context, *SearchMessagesRequest) (*MessageListResponse, error)
	// GetThread returns all messages belonging to a thread, ordered by creation time.
	GetThread(context.Context, *GetThreadRequest) (*MessageListResponse, error)
	// GetReplies returns all direct replies to a message.
	GetReplies(context.Context, *GetRepliesRequest) (*MessageListResponse, error)
	// SendMessage sends a message without going through the draft workflow.
	SendMessage(context.Context, *SendMessageRequest) (*MessageResponse, error)
	// UpdateFlags changes the read or archived status of a message.
	UpdateFlags(context.Context, *UpdateFlagsRequest) (*emptypb.Empty, error)
	// MoveMessage moves a message to a different folder.
	MoveMessage(context.Context, *MoveMessageRequest) (*emptypb.Empty, error)
	// DeleteMessage moves a message to trash.
	DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	// RestoreMessage restores a message from trash.
	RestoreMessage(context.Context, *RestoreMessageRequest) (*emptypb.Empty, error)
	// PermanentlyDeleteMessage hard-deletes a message from trash.
	PermanentlyDeleteMessage(context.Context, *PermanentlyDeleteMessageRequest) (*emptypb.Empty, error)
	// AddTag adds a tag to a message.
	AddTag(context.Context, *TagRequest) (*emptypb.Empty, error)
	// RemoveTag removes a tag from a message.
	RemoveTag(context.Context, *TagRequest) (*emptypb.Empty, error)
	// MarkAllRead marks all unread messages in a folder as read.
	MarkAllRead(context.Context, *MarkAllReadRequest) (*CountResponse, error)
	// BulkUpdateFlags changes the read/archived status of multiple messages.
	BulkUpdateFlags(context.Context, *BulkUpdateFlagsRequest) (*BulkResultResponse, error)
	// BulkMove moves multiple messages to a folder.
	BulkMove(context.Context, *BulkMoveRequest) (*BulkResultResponse, error)
	// BulkDelete moves multiple messages to trash.
	BulkDelete(context.Context, *BulkDeleteRequest) (*BulkResultResponse, error)
	// BulkPermanentlyDelete hard-deletes multiple messages from trash.
	BulkPermanentlyDelete(context.Context, *BulkPermanentlyDeleteRequest) (*BulkResultResponse, error)
	// BulkAddTag adds a tag to multiple messages.
	BulkAddTag(context.Context, *BulkTagRequest) (*BulkResultResponse, error)
	// BulkRemoveTag removes a tag from multiple messages.
	BulkRemoveTag(context.Context, *BulkTagRequest) (*BulkResultResponse, error)
	// ComposeDraft creates and saves a new draft.
	ComposeDraft(context.Context, *ComposeDraftRequest) (*DraftResponse, error)
	// UpdateDraft updates fields of an existing draft.
	// Only non-empty fields are applied; empty string fields are left unchanged.
	UpdateDraft(context.Context, *UpdateDraftRequest) (*DraftResponse, error)
	// ListDrafts lists all drafts for a user with pagination.
	ListDrafts(context.Context, *ListDraftsRequest) (*DraftListResponse, error)
	// DeleteDraft permanently deletes a draft.
	DeleteDraft(context.Context, *DeleteDraftRequest) (*emptypb.Empty, error)
	// SendDraft sends an existing draft.
	SendDraft(context.Context, *SendDraftRequest) (*MessageResponse, error)
	// GetStats returns aggregate statistics for a user's mailbox.
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	// UnreadCount returns the total number of unread messages for a user.
	UnreadCount(context.Context, *UnreadCountRequest) (*CountResponse, error)
	// ListFolders lists all folders (system and custom) in a user's mailbox.
	ListFolders(context.Context, *ListFoldersRequest) (*FolderListResponse, error)
	// StreamNotifications streams real-time notification events for a user.
	// The stream stays open until the client disconnects or the context is cancelled.
	// Pass last_event_id to replay missed events on reconnect.
	StreamNotifications(*StreamNotificationsRequest, grpc.ServerStreamingServer[NotificationEvent]) error
	mustEmbedUnimplementedMailboxServiceServer()
}

// UnimplementedMailboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailboxServiceServer struct{}

func (UnimplementedMailboxServiceServer) GetMessage(context.Context, *GetMessageRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedMailboxServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*MessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedMailboxServiceServer) SearchMessages(context.Context, *SearchMessagesRequest) (*MessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMessages not implemented")
}
func (UnimplementedMailboxServiceServer) GetThread(context.Context, *GetThreadRequest) (*MessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThread not implemented")
}
func (UnimplementedMailboxServiceServer) GetReplies(context.Context, *GetRepliesRequest) (*MessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplies not implemented")
}
func (UnimplementedMailboxServiceServer) SendMessage(context.Context, *SendMessageRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMailboxServiceServer) UpdateFlags(context.Context, *UpdateFlagsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFlags not implemented")
}
func (UnimplementedMailboxServiceServer) MoveMessage(context.Context, *MoveMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveMessage not implemented")
}
func (UnimplementedMailboxServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMailboxServiceServer) RestoreMessage(context.Context, *RestoreMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreMessage not implemented")
}
func (UnimplementedMailboxServiceServer) PermanentlyDeleteMessage(context.Context, *PermanentlyDeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PermanentlyDeleteMessage not implemented")
}
func (UnimplementedMailboxServiceServer) AddTag(context.Context, *TagRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTag not implemented")
}
func (UnimplementedMailboxServiceServer) RemoveTag(context.Context, *TagRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTag not implemented")
}
func (UnimplementedMailboxServiceServer) MarkAllRead(context.Context, *MarkAllReadRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedMailboxServiceServer) BulkUpdateFlags(context.Context, *BulkUpdateFlagsRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUpdateFlags not implemented")
}
func (UnimplementedMailboxServiceServer) BulkMove(context.Context, *BulkMoveRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkMove not implemented")
}
func (UnimplementedMailboxServiceServer) BulkDelete(context.Context, *BulkDeleteRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkDelete not implemented")
}
func (UnimplementedMailboxServiceServer) BulkPermanentlyDelete(context.Context, *BulkPermanentlyDeleteRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkPermanentlyDelete not implemented")
}
func (UnimplementedMailboxServiceServer) BulkAddTag(context.Context, *BulkTagRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkAddTag not implemented")
}
func (UnimplementedMailboxServiceServer) BulkRemoveTag(context.Context, *BulkTagRequest) (*BulkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkRemoveTag not implemented")
}
func (UnimplementedMailboxServiceServer) ComposeDraft(context.Context, *ComposeDraftRequest) (*DraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComposeDraft not implemented")
}
func (UnimplementedMailboxServiceServer) UpdateDraft(context.Context, *UpdateDraftRequest) (*DraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDraft not implemented")
}
func (UnimplementedMailboxServiceServer) ListDrafts(context.Context, *ListDraftsRequest) (*DraftListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrafts not implemented")
}
func (UnimplementedMailboxServiceServer) DeleteDraft(context.Context, *DeleteDraftRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDraft not implemented")
}
func (UnimplementedMailboxServiceServer) SendDraft(context.Context, *SendDraftRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDraft not implemented")
}
func (UnimplementedMailboxServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMailboxServiceServer) UnreadCount(context.Context, *UnreadCountRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnreadCount not implemented")
}
func (UnimplementedMailboxServiceServer) ListFolders(context.Context, *ListFoldersRequest) (*FolderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedMailboxServiceServer) StreamNotifications(*StreamNotificationsRequest, grpc.ServerStreamingServer[NotificationEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamNotifications not implemented")
}
func (UnimplementedMailboxServiceServer) mustEmbedUnimplementedMailboxServiceServer() {}
func (UnimplementedMailboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeMailboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailboxServiceServer will
// result in compilation errors.
type UnsafeMailboxServiceServer interface {
	mustEmbedUnimplementedMailboxServiceServer()
}

func RegisterMailboxServiceServer(s grpc.ServiceRegistrar, srv MailboxServiceServer) {
	// If the following call panics, it indicates UnimplementedMailboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailboxService_ServiceDesc, srv)
}

func _MailboxService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_SearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).SearchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_SearchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).SearchMessages(ctx, req.(*SearchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_GetThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).GetThread(ctx, req.(*GetThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_GetReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).GetReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_GetReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).GetReplies(ctx, req.(*GetRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_UpdateFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).UpdateFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_UpdateFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).UpdateFlags(ctx, req.(*UpdateFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_MoveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).MoveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_MoveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).MoveMessage(ctx, req.(*MoveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_RestoreMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).RestoreMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_RestoreMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).RestoreMessage(ctx, req.(*RestoreMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_PermanentlyDeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermanentlyDeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).PermanentlyDeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_PermanentlyDeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).PermanentlyDeleteMessage(ctx, req.(*PermanentlyDeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_AddTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).AddTag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_RemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).RemoveTag(ctx, req.(*TagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).MarkAllRead(ctx, req.(*MarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkUpdateFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdateFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkUpdateFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkUpdateFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkUpdateFlags(ctx, req.(*BulkUpdateFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkMove(ctx, req.(*BulkMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkDelete(ctx, req.(*BulkDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkPermanentlyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkPermanentlyDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkPermanentlyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkPermanentlyDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkPermanentlyDelete(ctx, req.(*BulkPermanentlyDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkAddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkAddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkAddTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkAddTag(ctx, req.(*BulkTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_BulkRemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).BulkRemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_BulkRemoveTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).BulkRemoveTag(ctx, req.(*BulkTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_ComposeDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComposeDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).ComposeDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_ComposeDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).ComposeDraft(ctx, req.(*ComposeDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_UpdateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).UpdateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_UpdateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).UpdateDraft(ctx, req.(*UpdateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_ListDrafts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDraftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).ListDrafts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_ListDrafts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).ListDrafts(ctx, req.(*ListDraftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_DeleteDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).DeleteDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_DeleteDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).DeleteDraft(ctx, req.(*DeleteDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_SendDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).SendDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_SendDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).SendDraft(ctx, req.(*SendDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_UnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).UnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_UnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).UnreadCount(ctx, req.(*UnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailboxServiceServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailboxService_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailboxServiceServer).ListFolders(ctx, req.(*ListFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailboxService_StreamNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MailboxServiceServer).StreamNotifications(m, &grpc.GenericServerStream[StreamNotificationsRequest, NotificationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MailboxService_StreamNotificationsServer = grpc.ServerStreamingServer[NotificationEvent]

// MailboxService_ServiceDesc is the grpc.ServiceDesc for MailboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mailbox.v1.MailboxService",
	HandlerType: (*MailboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _MailboxService_GetMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _MailboxService_ListMessages_Handler,
		},
		{
			MethodName: "SearchMessages",
			Handler:    _MailboxService_SearchMessages_Handler,
		},
		{
			MethodName: "GetThread",
			Handler:    _MailboxService_GetThread_Handler,
		},
		{
			MethodName: "GetReplies",
			Handler:    _MailboxService_GetReplies_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _MailboxService_SendMessage_Handler,
		},
		{
			MethodName: "UpdateFlags",
			Handler:    _MailboxService_UpdateFlags_Handler,
		},
		{
			MethodName: "MoveMessage",
			Handler:    _MailboxService_MoveMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MailboxService_DeleteMessage_Handler,
		},
		{
			MethodName: "RestoreMessage",
			Handler:    _MailboxService_RestoreMessage_Handler,
		},
		{
			MethodName: "PermanentlyDeleteMessage",
			Handler:    _MailboxService_PermanentlyDeleteMessage_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _MailboxService_AddTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _MailboxService_RemoveTag_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _MailboxService_MarkAllRead_Handler,
		},
		{
			MethodName: "BulkUpdateFlags",
			Handler:    _MailboxService_BulkUpdateFlags_Handler,
		},
		{
			MethodName: "BulkMove",
			Handler:    _MailboxService_BulkMove_Handler,
		},
		{
			MethodName: "BulkDelete",
			Handler:    _MailboxService_BulkDelete_Handler,
		},
		{
			MethodName: "BulkPermanentlyDelete",
			Handler:    _MailboxService_BulkPermanentlyDelete_Handler,
		},
		{
			MethodName: "BulkAddTag",
			Handler:    _MailboxService_BulkAddTag_Handler,
		},
		{
			MethodName: "BulkRemoveTag",
			Handler:    _MailboxService_BulkRemoveTag_Handler,
		},
		{
			MethodName: "ComposeDraft",
			Handler:    _MailboxService_ComposeDraft_Handler,
		},
		{
			MethodName: "UpdateDraft",
			Handler:    _MailboxService_UpdateDraft_Handler,
		},
		{
			MethodName: "ListDrafts",
			Handler:    _MailboxService_ListDrafts_Handler,
		},
		{
			MethodName: "DeleteDraft",
			Handler:    _MailboxService_DeleteDraft_Handler,
		},
		{
			MethodName: "SendDraft",
			Handler:    _MailboxService_SendDraft_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MailboxService_GetStats_Handler,
		},
		{
			MethodName: "UnreadCount",
			Handler:    _MailboxService_UnreadCount_Handler,
		},
		{
			MethodName: "ListFolders",
			Handler:    _MailboxService_ListFolders_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNotifications",
			Handler:       _MailboxService_StreamNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mailbox/v1/mailbox.proto",
}
